import Head from 'next/head';
import Banner from '@/components/Banner';
import Cars from '@/components/Cars';
import Categories from '@/components/Categories';
import Cities from '@/components/Cities';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import PopularCars from '@/components/PopularCars';
import Products from '@/components/Products';
import TopCategories from '@/components/TopCategories';

export default function Home() {
  return (
    <div>
      <Head>
        <title>letgo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>

        <Navbar />

        <Banner />

        <Categories />

        <TopCategories />

        <PopularCars />

        <Cars />

        <Products />

        <Cities />

        <Footer />
        
      </main>

    </div>
  )
}
